name: React App Deployment

on:
  push:
    branches: [ "master" ]

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Node.js environment
        uses: actions/setup-node@v4
        with:
          node-version: "20.12.2"
      - name: Install dependencies
        run: npm i
      - name: Test
        run: npm run test

  deploy:
    name: Deploy
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Node.js environment
        uses: actions/setup-node@v4
        with:
          node-version: "20.12.2"

      - name: Cache dependencies
        uses: actions/cache@v4
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-
      - name: Install dependencies
        run: npm i

      - name: Build
        run: npm run build

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist

  smoke-test:
    runs-on: ubuntu-latest
    name: Teste de aceitação
    needs: deploy
    steps:
    - name: Checkout do repositório
      uses: actions/checkout@v3

    - name: Instalar Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16'

    - name: Instalar dependências
      run: npm install

    - name: Aguardar deploy
      run: |
        echo "Aguardando 30 segundos para o deploy completar..."
        sleep 30  # Espera de 30 segundos para o deploy ser finalizado

    - name: Executar Cypress
      run: npm run cy:run